### ISSUE TITLE
[TS] Fails with children after #372

### ISSUE THREAD

**Issue by Ailrun** [paypal/glamorous#384]
This issue is originally issued by @denis-sokolov.
https://github.com/paypal/glamorous/pull/372#issuecomment-359251320

* `glamorous` version: 4.11.0 + #372
* `glamor` version: 2.20.40
* `react` version: 16.2.0
* `typescript` version: 2.6.1

Relevant code.

```typescript
<Div>
  <Div />
</Div>
```

What you did:
Add children to named built-in components.

What happened:

```
index.tsx(90,7): error TS2322: Type '{ children: Element; }' is not assignable to type 'IntrinsicAttributes & CSSProperties & ExtraGlamorousProps & HTMLProps<HTMLDivElement> & { childre...'.
  Type '{ children: Element; }' is not assignable to type 'CSSProperties'.
    Property 'children' is incompatible with index signature.
      Type 'Element' is not assignable to type 'string | number | SingleOrArray<CSSPropertiesCompleteSingle, "alignContent" | "alignItems" | "ali...'.
        Type 'Element' is not assignable to type '(string | number | {} | ("inherit" | "initial" | "unset" | "flex-start" | "flex-end" | "center" |...'.```
```

Reproduction:

Failed to reproduce.

Problem description:

Suggested solution:

It looks like already solved in up-to-date glamorous.

**Comment by Ailrun** [comment]
@luke-john the issue is added!

**Comment by denis-sokolov** [comment]
I am unable to reproduce the problem with the new glamorous version.

Either I messed up the original bug isolation, or there were other differences that have been changed in the meantime. Either way, I think the issue is solved until someone else comes with a similar complaint. Thank you for being so thorough and not dismissing my concerns, @Ailrun.

I had the original problem with glamor@2.20.40, glamorous@4.11.0+#372, react@16.2.0, typescript@2.6.1. Today I am unable to reproduce with glamor@2.20.40, glamorous@**4.11.6**, react@16.2.0, typescript@2.6.1.
